# Site settings
title: SwissPedHealth
subtitle: by SPHN & PHRT
email: swisspedhelth@proton.me
description: Pediatric Personalized Research Network Switzerland (SwissPedHealth) - a Joint National Pediatric Data Stream
# baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Haus der Akademien Laupenstrasse 7
city: Bern
# state: Bern
zip_code: 3001
country: Switzerland
phone: +41 21 693 18 74

# Social settings
# 500px_url:
# facebook_url:
# github_url: https://github.com/swisspedhealth
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://scholar.google.com/citations?hl=de&user=RPBxP1wAAAAJ
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/dylan-lawless-human-genomics/
pinterest_url:
slack_url:
# twitter_url: https://twitter.com/meddlaw

# Build settings
markdown: kramdown
